# Generated by Django 4.0 on 2022-01-01 21:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('age', models.CharField(max_length=100, verbose_name='age')),
                ('weight', models.CharField(max_length=100, verbose_name='Weight')),
                ('gender', models.CharField(choices=[('male', 'male'), ('fmale', 'fmale')], max_length=100, verbose_name='Gender')),
                ('number', models.CharField(max_length=100, verbose_name='Number')),
                ('Ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('Bed', models.CharField(max_length=100, verbose_name='Bed')),
                ('diagnoses', models.CharField(max_length=255, verbose_name='Diagnoses')),
                ('operation_type', models.CharField(max_length=255, verbose_name='Operation Type')),
                ('entry_date_time', models.DateTimeField(auto_now_add=True, verbose_name='entry date time')),
                ('operation_date_time', models.DateTimeField(verbose_name='operation date time')),
                ('leaving_date_time', models.DateTimeField(verbose_name='leaving date time')),
                ('medications', models.TextField(verbose_name='Medications')),
                ('operative_finding', models.TextField(max_length=255, verbose_name='operative finding')),
                ('operative_procedure', models.TextField(max_length=255, verbose_name='operative procedure')),
                ('operative_note', models.TextField(max_length=255, verbose_name='operative note')),
                ('specimen_to_laboratory', models.BooleanField(verbose_name='specimen to laboratory')),
                ('consultant_surgeon', models.CharField(max_length=255, verbose_name='consultant surgeon')),
                ('co_surgeon', models.CharField(max_length=255, verbose_name='co_surgeon')),
                ('surgeon', models.CharField(max_length=255, verbose_name='surgeon')),
                ('anesthetist', models.CharField(max_length=255, verbose_name='anesthetist')),
                ('nurse', models.CharField(max_length=255, verbose_name='nurse')),
                ('sponge_nurse', models.CharField(max_length=255, verbose_name='sponge_nurse')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='doctor_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
