# Generated by Django 4.0 on 2021-12-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('number', models.AutoField(auto_created=True, max_length=10000, primary_key=True, serialize=False, unique=True, verbose_name='Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('age', models.CharField(max_length=100, verbose_name='age')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('gender', models.CharField(choices=[('male', 'male'), ('fmale', 'fmale')], max_length=100, verbose_name='Gender')),
                ('Ward', models.CharField(max_length=100, verbose_name='Ward')),
                ('Bed', models.CharField(max_length=100, verbose_name='Bed')),
            ],
        ),
    ]
