# Generated by Django 4.0 on 2021-12-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_surgery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoses_Date_Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoses', models.CharField(max_length=255, verbose_name='Diagnoses')),
                ('operation_type', models.CharField(max_length=255, verbose_name='Operation Type')),
                ('entry_date_time', models.DateTimeField(auto_now_add=True, verbose_name='entry date time')),
                ('operation_date_time', models.DateTimeField(verbose_name='operation date time')),
                ('leaving_date_time', models.DateTimeField(verbose_name='leaving date time')),
                ('medications', models.TextField(verbose_name='Medications')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Number'),
        ),
    ]
