# Generated by Django 4.0 on 2022-01-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('heart_surgery', '0002_profile_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user', verbose_name='Added By'),
        ),
    ]
