# Generated by Django 4.0 on 2021-12-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_surgery', '0002_diagnoses_date_medications_alter_profile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operative_finding', models.CharField(max_length=255, verbose_name='operative finding')),
                ('operative_procedure', models.CharField(max_length=255, verbose_name='operative procedure')),
                ('operative_note', models.CharField(max_length=255, verbose_name='operative note')),
                ('specimen_to_laboratory', models.BooleanField(verbose_name='specimen to laboratory')),
            ],
        ),
    ]
