# Generated by Django 4.0 on 2021-12-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_surgery', '0003_operation_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_and_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_surgeon', models.CharField(max_length=255, verbose_name='consultant surgeon')),
                ('co_surgeon', models.CharField(max_length=255, verbose_name='co_surgeon')),
                ('surgeon', models.CharField(max_length=255, verbose_name='surgeon')),
                ('anesthetist', models.CharField(max_length=255, verbose_name='anesthetist')),
                ('nurse', models.CharField(max_length=255, verbose_name='nurse')),
                ('sponge_nurse', models.CharField(max_length=255, verbose_name='sponge_nurse')),
                ('doctor_name', models.CharField(max_length=255, verbose_name='doctor_name')),
            ],
        ),
    ]
