# Generated by Django 4.0 on 2021-12-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heart_surgery', '0004_doctors_and_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoses_date_medications',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Diagnoses_Date_Medications', to='heart_surgery.profile', verbose_name='patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors_and_staff',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Doctors_and_Staff', to='heart_surgery.profile', verbose_name='patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation_info',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Operation_Info', to='heart_surgery.profile', verbose_name='patient'),
            preserve_default=False,
        ),
    ]
